### ISSUE TITLE
Reduzindo código com Fórmula Matemática 

### ISSUE THREAD

**Issue by ghost** [JessicaNathany/calcula-desconto-produto#1]
# Uma sugestao para seu código, professora. 
 ao invés de usar: ```precoDesconto = preco - (preco * 5 / 100)```
pode fazer:          ``` precoDesconto = preco * 0.95```
---
_Na verdade estou usando essa oportunidade para fazer minha primeira Issue de verdade. Onde, quem me ensina atualmente pode deixar uma opiniao se a Issue foi boa ou nao._

**Comment by JessicaNathany** [comment]
Olá Alex tudo bom?

Pode me contextualizar? Rsrsrs
Você fala isso referente a última aula?

Vamos usar essa ideia na próxima, criar o método para dar desconto no
produto, ou fazer saque, depósito etc.. Isso ai, boa dica!

Continue praticando, crie novas classes em um arquivo novo, e repita os
exemplo. Proxima aula criaremos mais classes e métodos para por a cabeça
pra pensar de uma outra forma diferente.

Abraços

Atenciosamente,



..:: Jéssica Nathany ::..
JNCoder Software Ltda
CNPJ: 31.052.325/0001-41


*______________*


Em qua., 13 de jan. de 2021 às 18:10, Alex Cesar da Silva <
notifications@github.com> escreveu:

**Comment by ghost** [comment]
Boa noite, Professora Jessica! Há um método simplificado na matemática para
fazer contas. Esse método eu usava na calculadora para fazer a conta de
descontos e acréscimos, quando trabalhava com vendas.
 É muito simples: se eu tenho um produto de $29,00 e quero acrescentar 35%.
Ao invés de usarmos a fórmula tradicional, que aprendemos no ensino
fundamental: 29*35/100+29,  podemos usar: 29*1.35, e o resultado é 39.15:

 É só você transformar os 35% em .35 adicionando o 1 antes do ponto. Quando
é desconto invertermos, Se eu quero descontar 35% e sei que 100-35=65 sem
usar calculadora. Eu uso: 29*.65 paracalcular meu desconto e o resultado é:
18.85. Espero ter explicado bem. Não sou bom em explicar essas coisas.

Até a próxima.

**Comment by ghost** [comment]
Correção do segundo parágrafo: Para gerar desconto é só transformar os 35%
em.........

**Comment by JessicaNathany** [comment]
Olá Alex, bom dia.

Ah sim, entendi. Sim, na programação no código utilizamos essa fórmula
12*5/100 pra fazer a porcentagem.

Mas interessante sua abordagem, da pra gente fazer uns testes de mesa com
isso.

Abraços

Atenciosamente,



..:: Jéssica Nathany ::..
JNCoder Software Ltda
CNPJ: 31.052.325/0001-41


*______________*


Em qui., 14 de jan. de 2021 às 21:10, Alex Cesar da Silva <
notifications@github.com> escreveu:
